/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État de l'application */
        get: operations["read_system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historique des imports
         * @description Les imports passés, du plus récent au plus ancien, rejets compris.
         */
        get: operations["list_imports_api_v1_imports_get"];
        put?: never;
        /**
         * Importer un fichier
         * @description Importe un fichier avec le mapping fourni.
         *
         *     Réimporter le même fichier ne crée pas de doublon : l'opération est reconnue et
         *     l'historique renvoie l'import d'origine, avec le statut correspondant.
         */
        post: operations["import_file_api_v1_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'un import */
        get: operations["get_import_detail_api_v1_imports__import_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aperçu d'un fichier avant import
         * @description Lit un échantillon du fichier et en déduit la liste de ses champs.
         *
         *     Rien n'est écrit en base : l'aperçu sert à décider, pas à importer.
         */
        post: operations["preview_import_api_v1_imports_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Définitions des indicateurs
         * @description Le catalogue complet, consultable même quand aucune donnée n'a encore été importée.
         */
        get: operations["read_indicator_definitions_api_v1_metrics_definitions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Valeurs disponibles pour les filtres
         * @description Dérivées des traces importées, jamais d'une liste écrite en dur.
         */
        get: operations["read_filter_options_api_v1_metrics_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Synthèse des indicateurs */
        get: operations["read_kpi_summary_api_v1_metrics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Répartition des outils */
        get: operations["read_tool_breakdown_api_v1_metrics_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activité dans le temps */
        get: operations["read_activity_series_api_v1_metrics_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sessions du périmètre
         * @description Accepte les mêmes filtres que le dashboard, `session_id` compris.
         *
         *     C'est ce qui permet de partir d'un point de graphique — qui porte ses identifiants de
         *     sessions — et d'arriver aux enregistrements correspondants.
         */
        get: operations["list_sessions_api_v1_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'une session */
        get: operations["read_session_detail_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mapping/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Champs du modèle commun qu'un mapping peut renseigner
         * @description La liste fermée que l'agent IA vise et que le moteur d'import applique.
         *
         *     L'interface la lit ici plutôt que de la recopier : une liste dupliquée finirait par
         *     proposer des champs que le moteur refuse.
         */
        get: operations["mapping_fields_api_v1_mapping_fields_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mapping/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose une correspondance de champs pour un échantillon importé
         * @description Construit un échantillon à partir des enregistrements bruts envoyés, puis demande
         *     à l'agent IA configuré (`AI_PROVIDER`) de proposer une correspondance vers le modèle
         *     du domaine. Une correspondance non trouvée reste `None`, jamais une supposition.
         *
         *     Un fournisseur injoignable donne 502, pas une proposition vide : « le service n'a pas
         *     répondu » et « aucun champ ne correspond » ne doivent pas se ressembler.
         */
        post: operations["propose_mapping_api_v1_mapping_propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mapping/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Essaie un mapping sur un échantillon, sans rien écrire
         * @description Montre, champ par champ, les valeurs que le mapping lirait, et ce que l'import
         *     produirait — sessions, appels, anomalies, refus.
         *
         *     C'est l'étape qui manque entre « l'IA propose » et « on importe » : sans elle, la seule
         *     façon de vérifier un mapping est de lancer l'import et de nettoyer la base ensuite.
         */
        post: operations["preview_mapping_api_v1_mapping_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mappings enregistrés
         * @description Les mappings conservés, du plus récemment modifié au plus ancien.
         */
        get: operations["list_mappings_api_v1_mappings_get"];
        put?: never;
        /**
         * Enregistre un mapping vérifié
         * @description Conserve le mapping sous ce nom, en remplaçant celui qui le portait déjà.
         *
         *     Le mapping est validé avant d'être conservé : un mapping inapplicable enregistré
         *     aujourd'hui deviendrait une panne inexplicable le jour où quelqu'un le rechargerait.
         */
        post: operations["save_mapping_api_v1_mappings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mappings/{mapping_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Retire un mapping de la bibliothèque */
        delete: operations["delete_mapping_api_v1_mappings__mapping_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityPointResponse */
        ActivityPointResponse: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Sessions */
            sessions: number;
            /** Model Calls */
            model_calls: number;
            /** Tool Calls */
            tool_calls: number;
            /** Session Ids */
            session_ids: string[];
        };
        /** ActivitySeriesResponse */
        ActivitySeriesResponse: {
            /** Points */
            points: components["schemas"]["ActivityPointResponse"][];
            /**
             * Undated Sessions
             * @description Sessions sans horodatage, donc absentes de la série. Comptées à part plutôt que retirées en silence.
             */
            undated_sessions: number;
            /** Undated Model Calls */
            undated_model_calls: number;
            /** Undated Tool Calls */
            undated_tool_calls: number;
            /** Has Undated Records */
            has_undated_records: boolean;
        };
        /** AggregateResponse */
        AggregateResponse: {
            /**
             * Value
             * @description Valeur calculée, ou null si la mesure n'est pas disponible. Jamais 0 pour signifier une absence.
             */
            value: number | null;
            /** Unit */
            unit: string;
            /**
             * Available
             * @description Faux quand aucune donnée du périmètre ne renseigne la mesure.
             */
            available: boolean;
            /**
             * Partial
             * @description Vrai quand la valeur ne porte que sur une partie du périmètre.
             */
            partial: boolean;
            /**
             * Covered
             * @description Enregistrements ayant réellement renseigné la mesure.
             */
            covered: number;
            /**
             * Total
             * @description Enregistrements du périmètre.
             */
            total: number;
            /**
             * Coverage
             * @description Part couverte, de 0 à 1. Null si le périmètre est vide.
             */
            coverage: number | null;
        };
        /** Body_import_file_api_v1_imports_post */
        Body_import_file_api_v1_imports_post: {
            /**
             * File
             * @description Fichier JSONL, CSV ou Parquet.
             */
            file: string;
            /**
             * Source Name
             * @description Nom de la source à créer ou à réutiliser.
             */
            source_name: string;
            /**
             * Mapping
             * @description Correspondances champ du modèle → champ du fichier, en JSON. Omis, une correspondance à l'identique est tentée.
             */
            mapping?: string | null;
        };
        /** Body_preview_import_api_v1_imports_preview_post */
        Body_preview_import_api_v1_imports_preview_post: {
            /**
             * File
             * @description Fichier JSONL, CSV ou Parquet.
             */
            file: string;
        };
        /** FieldMappingResponse */
        FieldMappingResponse: {
            /** Target Field */
            target_field: string;
            /** Source Field */
            source_field: string | null;
            /** Confidence */
            confidence: number | null;
            /** Note */
            note: string | null;
        };
        /**
         * FieldOutcomeResponse
         * @description Ce qu'un champ donnerait sur l'échantillon.
         */
        FieldOutcomeResponse: {
            /** Target Field */
            target_field: string;
            /** Path */
            path: string | null;
            /** Scope */
            scope: string;
            /** Required */
            required: boolean;
            /**
             * Examples
             * @description Valeurs réellement lues, tronquées.
             */
            examples: string[];
            /**
             * Resolved
             * @description Enregistrements où le chemin mène à une valeur.
             */
            resolved: number;
            /** Total */
            total: number;
        };
        /**
         * FilterOptionsResponse
         * @description Les valeurs sur lesquelles il est possible de filtrer, dérivées des traces importées.
         */
        FilterOptionsResponse: {
            /** Sources */
            sources: string[];
            /** Agents */
            agents: string[];
            /** Models */
            models: string[];
            /**
             * First Day
             * @description Première journée observée. Null si aucun enregistrement n'est horodaté.
             */
            first_day: string | null;
            /** Last Day */
            last_day: string | null;
            /**
             * Is Empty
             * @description Vrai quand aucune trace n'a été importée.
             */
            is_empty: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportDetailResponse
         * @description Le bilan d'un import, avec le détail de ses rejets.
         *
         *     Une liste vide veut dire que l'import n'a rien refusé — pas qu'on ne sait pas ce qu'il
         *     a refusé.
         */
        ImportDetailResponse: {
            /** Id */
            id: string;
            /** Source Name */
            source_name: string;
            /** Filename */
            filename: string;
            /** Format */
            format: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
            /**
             * Status
             * @description « completed » quand l'import a abouti, « duplicate » quand le fichier avait déjà été importé.
             */
            status: string;
            /** Records Imported */
            records_imported: number;
            /** Duplicates Count */
            duplicates_count: number;
            /** Rejected Count */
            rejected_count: number;
            /**
             * Missing Data Count
             * @description Nombre d'informations manquantes relevées pendant la normalisation.
             */
            missing_data_count: number;
            /**
             * Rejections
             * @default []
             */
            rejections: components["schemas"]["ImportRejectionResponse"][];
        };
        /** ImportListResponse */
        ImportListResponse: {
            /** Imports */
            imports: components["schemas"]["ImportRecordResponse"][];
        };
        /**
         * ImportPreviewResponse
         * @description Ce qu'on peut dire d'un fichier avant de l'importer.
         */
        ImportPreviewResponse: {
            /** Filename */
            filename: string;
            /** Format */
            format: string;
            /**
             * Row Count Sample
             * @description Nombre de lignes de l'échantillon lu.
             */
            row_count_sample: number;
            /**
             * Columns
             * @description Champs rencontrés dans l'échantillon, dans leur ordre d'apparition.
             */
            columns: string[];
            /** Sample Rows */
            sample_rows: {
                [key: string]: unknown;
            }[];
        };
        /**
         * ImportRecordResponse
         * @description Le bilan d'une opération d'import.
         */
        ImportRecordResponse: {
            /** Id */
            id: string;
            /** Source Name */
            source_name: string;
            /** Filename */
            filename: string;
            /** Format */
            format: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
            /**
             * Status
             * @description « completed » quand l'import a abouti, « duplicate » quand le fichier avait déjà été importé.
             */
            status: string;
            /** Records Imported */
            records_imported: number;
            /** Duplicates Count */
            duplicates_count: number;
            /** Rejected Count */
            rejected_count: number;
            /**
             * Missing Data Count
             * @description Nombre d'informations manquantes relevées pendant la normalisation.
             */
            missing_data_count: number;
        };
        /**
         * ImportRejectionResponse
         * @description Un enregistrement refusé, et la raison du refus.
         */
        ImportRejectionResponse: {
            /**
             * Line Number
             * @description Rang de l'enregistrement dans le fichier, depuis 1.
             */
            line_number: number;
            /** Reason */
            reason: string;
            /**
             * Raw Preview
             * @description Début de l'enregistrement d'origine, pour le reconnaître.
             */
            raw_preview: string | null;
        };
        /**
         * ImportSampleRequest
         * @description Échantillon brut envoyé par le client : un aperçu du fichier à importer.
         */
        ImportSampleRequest: {
            /**
             * Source Format
             * @description Format du fichier source : jsonl, csv, parquet.
             */
            source_format: string;
            /**
             * Records
             * @description Quelques enregistrements bruts, tels que lus dans le fichier.
             */
            records: {
                [key: string]: unknown;
            }[];
        };
        /**
         * IndicatorCatalogResponse
         * @description Le catalogue des définitions, consultable même sans aucune donnée importée.
         */
        IndicatorCatalogResponse: {
            /** Definitions */
            definitions: components["schemas"]["IndicatorDefinitionResponse"][];
        };
        /**
         * IndicatorDefinitionResponse
         * @description La définition d'un indicateur, telle qu'elle doit être consultable dans l'interface.
         */
        IndicatorDefinitionResponse: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Computation */
            computation: string;
            /** Scope */
            scope: string;
            /** Missing Values */
            missing_values: string;
            /**
             * Comparability
             * @description « comparable » ou « source_specific ». Un indicateur propre à une source ne doit pas être agrégé silencieusement avec les autres.
             */
            comparability: string;
            /**
             * Kind
             * @description « count » ou « measure ». La couverture n'a de sens que pour une mesure : un dénombrement est complet par construction.
             */
            kind: string;
        };
        /** IndicatorResponse */
        IndicatorResponse: {
            definition: components["schemas"]["IndicatorDefinitionResponse"];
            aggregate: components["schemas"]["AggregateResponse"];
            /** Sources */
            sources: string[];
            /**
             * Mixes Incomparable Sources
             * @description Vrai quand ce chiffre agrège plusieurs sources qui ne le mesurent pas de la même façon. L'interface doit alors le signaler.
             */
            mixes_incomparable_sources: boolean;
        };
        /** KpiSummaryResponse */
        KpiSummaryResponse: {
            /** Indicators */
            indicators: components["schemas"]["IndicatorResponse"][];
        };
        /**
         * MappingContractResponse
         * @description La liste fermée des champs visés, telle que le domaine la déclare.
         *
         *     L'interface la lit au lieu de la recopier : une liste dupliquée finirait par proposer
         *     des champs que le moteur d'import refuse.
         */
        MappingContractResponse: {
            /** Fields */
            fields: components["schemas"]["TargetFieldResponse"][];
        };
        /**
         * MappingPreviewRequest
         * @description Un échantillon et un mapping à essayer dessus, sans rien écrire.
         */
        MappingPreviewRequest: {
            /** Records */
            records: {
                [key: string]: unknown;
            }[];
            /** Mapping */
            mapping: {
                [key: string]: string | null;
            };
            /**
             * Source Name
             * @default
             */
            source_name: string;
        };
        /**
         * MappingPreviewResponse
         * @description Ce que l'import produirait avec ce mapping, sans l'avoir lancé.
         */
        MappingPreviewResponse: {
            /** Fields */
            fields: components["schemas"]["FieldOutcomeResponse"][];
            /** Records */
            records: number;
            /** Sessions */
            sessions: number;
            /** Model Calls */
            model_calls: number;
            /** Tool Calls */
            tool_calls: number;
            /** Issues */
            issues: string[];
            /** Rejected */
            rejected: number;
        };
        /** MappingProposalResponse */
        MappingProposalResponse: {
            /** Mappings */
            mappings: components["schemas"]["FieldMappingResponse"][];
            /** Unresolved Notes */
            unresolved_notes: string[];
        };
        /**
         * SaveMappingRequest
         * @description Un mapping vérifié, à conserver sous un nom.
         */
        SaveMappingRequest: {
            /**
             * Name
             * @description Nom sous lequel le retrouver. Réenregistrer remplace.
             */
            name: string;
            /** Source Name */
            source_name?: string | null;
            /** Mapping */
            mapping: {
                [key: string]: string | null;
            };
        };
        /** SavedMappingListResponse */
        SavedMappingListResponse: {
            /** Mappings */
            mappings: components["schemas"]["SavedMappingResponse"][];
        };
        /** SavedMappingResponse */
        SavedMappingResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Source Name */
            source_name: string | null;
            /** Mapping */
            mapping: {
                [key: string]: string | null;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SessionDetailResponse */
        SessionDetailResponse: {
            /** Session Id */
            session_id: string;
            /** Source */
            source: string;
            /** Agent */
            agent: string | null;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** @description Durée de la session. Indisponible — et non nulle — quand les horodatages manquent. */
            duration: components["schemas"]["AggregateResponse"];
            input_tokens: components["schemas"]["AggregateResponse"];
            /** Model Calls */
            model_calls: number;
            /** Tool Calls */
            tool_calls: number;
            /** Failed Tool Calls */
            failed_tool_calls: number;
            /** Events */
            events: components["schemas"]["SessionEventResponse"][];
        };
        /** SessionEventResponse */
        SessionEventResponse: {
            /**
             * Kind
             * @description « model_call » ou « tool_call ».
             */
            kind: string;
            /** Label */
            label: string;
            /**
             * Occurred At
             * @description Null quand la trace ne date pas l'événement. Ces événements sont conservés en fin de chronologie plutôt que supprimés.
             */
            occurred_at: string | null;
            /** Input Tokens */
            input_tokens: number | null;
            /**
             * Is Error
             * @description Null quand la source ne publie pas l'issue de l'appel — un troisième état, distinct de réussi et d'échoué.
             */
            is_error: boolean | null;
            /** Latency Ms */
            latency_ms: number | null;
        };
        /** SessionListResponse */
        SessionListResponse: {
            /** Sessions */
            sessions: components["schemas"]["SessionSummaryResponse"][];
            /**
             * Total
             * @description Nombre de sessions du périmètre, y compris celles que la liste ne montre pas.
             */
            total: number;
            /** Truncated */
            truncated: boolean;
        };
        /**
         * SessionSummaryResponse
         * @description Une session vue de loin, telle qu'elle apparaît dans une liste.
         */
        SessionSummaryResponse: {
            /** Session Id */
            session_id: string;
            /** Source */
            source: string;
            /** Agent */
            agent: string | null;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            duration: components["schemas"]["AggregateResponse"];
            /** Model Calls */
            model_calls: number;
            /** Tool Calls */
            tool_calls: number;
            input_tokens: components["schemas"]["AggregateResponse"];
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            /**
             * Version
             * @description Version de l'application.
             */
            version: string;
            /**
             * Database
             * @description État du stockage : « ok » ou « unavailable ».
             */
            database: string;
            /**
             * Operational
             * @description Vrai si l'application peut rendre son service. Une application démarrée mais privée de son stockage est en ligne sans être opérationnelle.
             */
            operational: boolean;
        };
        /**
         * TargetFieldResponse
         * @description Un champ du modèle commun qu'un mapping peut renseigner.
         */
        TargetFieldResponse: {
            /** Key */
            key: string;
            /**
             * Scope
             * @description session, model_call, tool_call ou collection.
             */
            scope: string;
            /** Description */
            description: string;
            /** Required */
            required: boolean;
        };
        /** ToolBreakdownResponse */
        ToolBreakdownResponse: {
            /** Usages */
            usages: components["schemas"]["ToolUsageResponse"][];
            /** Tool Calls Total */
            tool_calls_total: number;
            /** Distinct Tools */
            distinct_tools: number;
        };
        /** ToolUsageResponse */
        ToolUsageResponse: {
            /** Tool Name */
            tool_name: string;
            calls: components["schemas"]["AggregateResponse"];
            share: components["schemas"]["AggregateResponse"];
            error_rate: components["schemas"]["AggregateResponse"];
            median_latency: components["schemas"]["AggregateResponse"];
            /**
             * Session Ids
             * @description Sessions où cet outil apparaît. Permet de revenir du graphique aux enregistrements correspondants.
             */
            session_ids: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_system_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    list_imports_api_v1_imports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportListResponse"];
                };
            };
        };
    };
    import_file_api_v1_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_file_api_v1_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRecordResponse"];
                };
            };
            /** @description Format non reconnu, ou mapping invalide. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_import_detail_api_v1_imports__import_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportDetailResponse"];
                };
            };
            /** @description Aucun import ne porte cet identifiant. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_import_api_v1_imports_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_import_api_v1_imports_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreviewResponse"];
                };
            };
            /** @description Format de fichier non reconnu. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_indicator_definitions_api_v1_metrics_definitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorCatalogResponse"];
                };
            };
        };
    };
    read_filter_options_api_v1_metrics_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterOptionsResponse"];
                };
            };
        };
    };
    read_kpi_summary_api_v1_metrics_summary_get: {
        parameters: {
            query?: {
                /** @description Sources retenues. */
                source?: string[] | null;
                /** @description Agents retenus. */
                agent?: string[] | null;
                /** @description Modèles retenus. */
                model?: string[] | null;
                /** @description Sessions retenues. */
                session_id?: string[] | null;
                /** @description Début de période, inclus. */
                since?: string | null;
                /** @description Fin de période, incluse. */
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_tool_breakdown_api_v1_metrics_tools_get: {
        parameters: {
            query?: {
                /** @description Sources retenues. */
                source?: string[] | null;
                /** @description Agents retenus. */
                agent?: string[] | null;
                /** @description Modèles retenus. */
                model?: string[] | null;
                /** @description Sessions retenues. */
                session_id?: string[] | null;
                /** @description Début de période, inclus. */
                since?: string | null;
                /** @description Fin de période, incluse. */
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolBreakdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_activity_series_api_v1_metrics_activity_get: {
        parameters: {
            query?: {
                /** @description Sources retenues. */
                source?: string[] | null;
                /** @description Agents retenus. */
                agent?: string[] | null;
                /** @description Modèles retenus. */
                model?: string[] | null;
                /** @description Sessions retenues. */
                session_id?: string[] | null;
                /** @description Début de période, inclus. */
                since?: string | null;
                /** @description Fin de période, incluse. */
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_sessions_get: {
        parameters: {
            query?: {
                /** @description Sources retenues. */
                source?: string[] | null;
                /** @description Agents retenus. */
                agent?: string[] | null;
                /** @description Modèles retenus. */
                model?: string[] | null;
                /** @description Sessions retenues. */
                session_id?: string[] | null;
                /** @description Début de période, inclus. */
                since?: string | null;
                /** @description Fin de période, incluse. */
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_session_detail_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailResponse"];
                };
            };
            /** @description Aucune session ne porte cet identifiant. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mapping_fields_api_v1_mapping_fields_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingContractResponse"];
                };
            };
        };
    };
    propose_mapping_api_v1_mapping_propose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportSampleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingProposalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Le fournisseur d'IA configuré n'a pas répondu. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    preview_mapping_api_v1_mapping_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingPreviewResponse"];
                };
            };
            /** @description Mapping inapplicable. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_mappings_api_v1_mappings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedMappingListResponse"];
                };
            };
        };
    };
    save_mapping_api_v1_mappings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveMappingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedMappingResponse"];
                };
            };
            /** @description Mapping inapplicable, ou sans nom. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_mapping_api_v1_mappings__mapping_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mapping_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Aucun mapping enregistré ne porte cet identifiant. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
