/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État de l'application */
        get: operations["read_system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Définitions des indicateurs
         * @description Le catalogue complet, consultable même quand aucune donnée n'a encore été importée.
         */
        get: operations["read_indicator_definitions_api_v1_metrics_definitions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Valeurs disponibles pour les filtres
         * @description Dérivées des traces importées, jamais d'une liste écrite en dur.
         */
        get: operations["read_filter_options_api_v1_metrics_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Synthèse des indicateurs */
        get: operations["read_kpi_summary_api_v1_metrics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Répartition des outils */
        get: operations["read_tool_breakdown_api_v1_metrics_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activité dans le temps */
        get: operations["read_activity_series_api_v1_metrics_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sessions du périmètre
         * @description Accepte les mêmes filtres que le dashboard, `session_id` compris.
         *
         *     C'est ce qui permet de partir d'un point de graphique — qui porte ses identifiants de
         *     sessions — et d'arriver aux enregistrements correspondants.
         */
        get: operations["list_sessions_api_v1_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Détail d'une session */
        get: operations["read_session_detail_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mapping/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose une correspondance de champs pour un échantillon importé
         * @description Construit un échantillon à partir des enregistrements bruts envoyés, puis demande
         *     à l'agent IA configuré (`AI_PROVIDER`) de proposer une correspondance vers le modèle
         *     du domaine. Une correspondance non trouvée reste `None`, jamais une supposition.
         */
        post: operations["propose_mapping_api_v1_mapping_propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityPointResponse */
        ActivityPointResponse: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Sessions */
            sessions: number;
            /** Model Calls */
            model_calls: number;
            /** Tool Calls */
            tool_calls: number;
            /** Session Ids */
            session_ids: string[];
        };
        /** ActivitySeriesResponse */
        ActivitySeriesResponse: {
            /** Points */
            points: components["schemas"]["ActivityPointResponse"][];
            /**
             * Undated Sessions
             * @description Sessions sans horodatage, donc absentes de la série. Comptées à part plutôt que retirées en silence.
             */
            undated_sessions: number;
            /** Undated Model Calls */
            undated_model_calls: number;
            /** Undated Tool Calls */
            undated_tool_calls: number;
            /** Has Undated Records */
            has_undated_records: boolean;
        };
        /** AggregateResponse */
        AggregateResponse: {
            /**
             * Value
             * @description Valeur calculée, ou null si la mesure n'est pas disponible. Jamais 0 pour signifier une absence.
             */
            value: number | null;
            /** Unit */
            unit: string;
            /**
             * Available
             * @description Faux quand aucune donnée du périmètre ne renseigne la mesure.
             */
            available: boolean;
            /**
             * Partial
             * @description Vrai quand la valeur ne porte que sur une partie du périmètre.
             */
            partial: boolean;
            /**
             * Covered
             * @description Enregistrements ayant réellement renseigné la mesure.
             */
            covered: number;
            /**
             * Total
             * @description Enregistrements du périmètre.
             */
            total: number;
            /**
             * Coverage
             * @description Part couverte, de 0 à 1. Null si le périmètre est vide.
             */
            coverage: number | null;
        };
        /** FieldMappingResponse */
        FieldMappingResponse: {
            /** Target Field */
            target_field: string;
            /** Source Field */
            source_field: string | null;
            /** Confidence */
            confidence: number | null;
            /** Note */
            note: string | null;
        };
        /**
         * FilterOptionsResponse
         * @description Les valeurs sur lesquelles il est possible de filtrer, dérivées des traces importées.
         */
        FilterOptionsResponse: {
            /** Sources */
            sources: string[];
            /** Agents */
            agents: string[];
            /** Models */
            models: string[];
            /**
             * First Day
             * @description Première journée observée. Null si aucun enregistrement n'est horodaté.
             */
            first_day: string | null;
            /** Last Day */
            last_day: string | null;
            /**
             * Is Empty
             * @description Vrai quand aucune trace n'a été importée.
             */
            is_empty: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportSampleRequest
         * @description Échantillon brut envoyé par le client : un aperçu du fichier à importer.
         */
        ImportSampleRequest: {
            /**
             * Source Format
             * @description Format du fichier source : jsonl, csv, parquet.
             */
            source_format: string;
            /**
             * Records
             * @description Quelques enregistrements bruts, tels que lus dans le fichier.
             */
            records: {
                [key: string]: unknown;
            }[];
        };
        /**
         * IndicatorCatalogResponse
         * @description Le catalogue des définitions, consultable même sans aucune donnée importée.
         */
        IndicatorCatalogResponse: {
            /** Definitions */
            definitions: components["schemas"]["IndicatorDefinitionResponse"][];
        };
        /**
         * IndicatorDefinitionResponse
         * @description La définition d'un indicateur, telle qu'elle doit être consultable dans l'interface.
         */
        IndicatorDefinitionResponse: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Computation */
            computation: string;
            /** Scope */
            scope: string;
            /** Missing Values */
            missing_values: string;
            /**
             * Comparability
             * @description « comparable » ou « source_specific ». Un indicateur propre à une source ne doit pas être agrégé silencieusement avec les autres.
             */
            comparability: string;
        };
        /** IndicatorResponse */
        IndicatorResponse: {
            definition: components["schemas"]["IndicatorDefinitionResponse"];
            aggregate: components["schemas"]["AggregateResponse"];
            /** Sources */
            sources: string[];
            /**
             * Mixes Incomparable Sources
             * @description Vrai quand ce chiffre agrège plusieurs sources qui ne le mesurent pas de la même façon. L'interface doit alors le signaler.
             */
            mixes_incomparable_sources: boolean;
        };
        /** KpiSummaryResponse */
        KpiSummaryResponse: {
            /** Indicators */
            indicators: components["schemas"]["IndicatorResponse"][];
        };
        /** MappingProposalResponse */
        MappingProposalResponse: {
            /** Mappings */
            mappings: components["schemas"]["FieldMappingResponse"][];
            /** Unresolved Notes */
            unresolved_notes: string[];
        };
        /** SessionDetailResponse */
        SessionDetailResponse: {
            /** Session Id */
            session_id: string;
            /** Source */
            source: string;
            /** Agent */
            agent: string | null;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** @description Durée de la session. Indisponible — et non nulle — quand les horodatages manquent. */
            duration: components["schemas"]["AggregateResponse"];
            input_tokens: components["schemas"]["AggregateResponse"];
            /** Model Calls */
            model_calls: number;
            /** Tool Calls */
            tool_calls: number;
            /** Failed Tool Calls */
            failed_tool_calls: number;
            /** Events */
            events: components["schemas"]["SessionEventResponse"][];
        };
        /** SessionEventResponse */
        SessionEventResponse: {
            /**
             * Kind
             * @description « model_call » ou « tool_call ».
             */
            kind: string;
            /** Label */
            label: string;
            /**
             * Occurred At
             * @description Null quand la trace ne date pas l'événement. Ces événements sont conservés en fin de chronologie plutôt que supprimés.
             */
            occurred_at: string | null;
            /** Input Tokens */
            input_tokens: number | null;
            /**
             * Is Error
             * @description Null quand la source ne publie pas l'issue de l'appel — un troisième état, distinct de réussi et d'échoué.
             */
            is_error: boolean | null;
            /** Latency Ms */
            latency_ms: number | null;
        };
        /** SessionListResponse */
        SessionListResponse: {
            /** Sessions */
            sessions: components["schemas"]["SessionSummaryResponse"][];
            /**
             * Total
             * @description Nombre de sessions du périmètre, y compris celles que la liste ne montre pas.
             */
            total: number;
            /** Truncated */
            truncated: boolean;
        };
        /**
         * SessionSummaryResponse
         * @description Une session vue de loin, telle qu'elle apparaît dans une liste.
         */
        SessionSummaryResponse: {
            /** Session Id */
            session_id: string;
            /** Source */
            source: string;
            /** Agent */
            agent: string | null;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            duration: components["schemas"]["AggregateResponse"];
            /** Model Calls */
            model_calls: number;
            /** Tool Calls */
            tool_calls: number;
            input_tokens: components["schemas"]["AggregateResponse"];
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            /**
             * Version
             * @description Version de l'application.
             */
            version: string;
            /**
             * Database
             * @description État du stockage : « ok » ou « unavailable ».
             */
            database: string;
            /**
             * Operational
             * @description Vrai si l'application peut rendre son service. Une application démarrée mais privée de son stockage est en ligne sans être opérationnelle.
             */
            operational: boolean;
        };
        /** ToolBreakdownResponse */
        ToolBreakdownResponse: {
            /** Usages */
            usages: components["schemas"]["ToolUsageResponse"][];
            /** Tool Calls Total */
            tool_calls_total: number;
            /** Distinct Tools */
            distinct_tools: number;
        };
        /** ToolUsageResponse */
        ToolUsageResponse: {
            /** Tool Name */
            tool_name: string;
            calls: components["schemas"]["AggregateResponse"];
            share: components["schemas"]["AggregateResponse"];
            error_rate: components["schemas"]["AggregateResponse"];
            median_latency: components["schemas"]["AggregateResponse"];
            /**
             * Session Ids
             * @description Sessions où cet outil apparaît. Permet de revenir du graphique aux enregistrements correspondants.
             */
            session_ids: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_system_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    read_indicator_definitions_api_v1_metrics_definitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorCatalogResponse"];
                };
            };
        };
    };
    read_filter_options_api_v1_metrics_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterOptionsResponse"];
                };
            };
        };
    };
    read_kpi_summary_api_v1_metrics_summary_get: {
        parameters: {
            query?: {
                /** @description Sources retenues. */
                source?: string[] | null;
                /** @description Agents retenus. */
                agent?: string[] | null;
                /** @description Modèles retenus. */
                model?: string[] | null;
                /** @description Sessions retenues. */
                session_id?: string[] | null;
                /** @description Début de période, inclus. */
                since?: string | null;
                /** @description Fin de période, incluse. */
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_tool_breakdown_api_v1_metrics_tools_get: {
        parameters: {
            query?: {
                /** @description Sources retenues. */
                source?: string[] | null;
                /** @description Agents retenus. */
                agent?: string[] | null;
                /** @description Modèles retenus. */
                model?: string[] | null;
                /** @description Sessions retenues. */
                session_id?: string[] | null;
                /** @description Début de période, inclus. */
                since?: string | null;
                /** @description Fin de période, incluse. */
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolBreakdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_activity_series_api_v1_metrics_activity_get: {
        parameters: {
            query?: {
                /** @description Sources retenues. */
                source?: string[] | null;
                /** @description Agents retenus. */
                agent?: string[] | null;
                /** @description Modèles retenus. */
                model?: string[] | null;
                /** @description Sessions retenues. */
                session_id?: string[] | null;
                /** @description Début de période, inclus. */
                since?: string | null;
                /** @description Fin de période, incluse. */
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_sessions_get: {
        parameters: {
            query?: {
                /** @description Sources retenues. */
                source?: string[] | null;
                /** @description Agents retenus. */
                agent?: string[] | null;
                /** @description Modèles retenus. */
                model?: string[] | null;
                /** @description Sessions retenues. */
                session_id?: string[] | null;
                /** @description Début de période, inclus. */
                since?: string | null;
                /** @description Fin de période, incluse. */
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_session_detail_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailResponse"];
                };
            };
            /** @description Aucune session ne porte cet identifiant. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_mapping_api_v1_mapping_propose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportSampleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingProposalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
