"""ajoute l issue des appels d outils

Revision ID: 1112ec03fd48
Revises: a220812961a8
Create Date: 2026-09-10 10:03:27.577263
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1112ec03fd48'
down_revision: str | None = 'a220812961a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_calls', sa.Column('is_error', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_calls', 'is_error')
    # ### end Alembic commands ###
