"""conserve le detail des rejets d import

Une table plutot qu'un compteur sur « imports » : un nombre dit qu'il y a eu un probleme,
il ne permet pas de le corriger. Chaque rejet garde son rang dans le fichier et le debut de
la ligne refusee.

Revision ID: f82eeb1c4496
Revises: 1112ec03fd48
Create Date: 2026-09-10 14:17:26.477564
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f82eeb1c4496'
down_revision: str | None = '1112ec03fd48'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_rejections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_id', sa.Uuid(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('raw_preview', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_rejections_import_id'), 'import_rejections', ['import_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_rejections_import_id'), table_name='import_rejections')
    op.drop_table('import_rejections')
    # ### end Alembic commands ###
